# Generated by Django 4.2.28 on 2026-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_conductorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
