# Generated by Django 4.2.28 on 2026-02-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conductorprofile_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('conductor', 'Conductor'), ('comedor', 'Comedor')], default='conductor', max_length=20),
        ),
    ]
