# Generated by Django 4.2.28 on 2026-02-26 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0006_rutaprogramada_lugar_vales'),
        ('accounts', '0005_alter_conductorprofile_clave_alter_user_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosaldo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ValeConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_consumidos', to='accounts.conductorprofile')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_consumidos', to='recargas.rutaprogramada')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
