# Generated by Django 4.2.28 on 2026-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_movimientosaldo_creado_por_valeconsumido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('preceptor', 'Preceptor'), ('conductor', 'Conductor'), ('comedor', 'Comedor'), ('auditor', 'Auditor')], default='conductor', max_length=20),
        ),
    ]
