# Generated by Django 4.2.28 on 2026-02-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_conductorprofile_clave_alter_user_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=10)),
                ('hora_salida', models.TimeField()),
                ('dias_operacion', models.TextField(default='[]')),
                ('conductores_requeridos', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=50)),
                ('vales', models.IntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='recargas.rutaprogramada')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('conductor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_conductor1', to='accounts.conductorprofile')),
                ('conductor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_conductor2', to='accounts.conductorprofile')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='recargas.rutaprogramada')),
            ],
        ),
    ]
