# Generated by Django 4.2.28 on 2026-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaprogramada',
            name='destino',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rutaprogramada',
            name='origen',
            field=models.CharField(max_length=50),
        ),
    ]
