# Generated by Django 4.2.28 on 2026-02-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0002_alter_rutaprogramada_destino_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RutaLugar',
        ),
    ]
