# Generated by Django 4.2.28 on 2026-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0003_delete_rutalugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaprogramada',
            name='dias_operacion',
            field=models.TextField(default='[L,M,W,J,V]'),
        ),
    ]
