# Generated by Django 4.2.28 on 2026-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0004_alter_rutaprogramada_dias_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaprogramada',
            name='destino',
            field=models.CharField(choices=[('AOA', 'AOA'), ('VEV', 'VEV'), ('JAV', 'JAV'), ('CHK', 'CHK'), ('CBV', 'CBV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rutaprogramada',
            name='dias_operacion',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='rutaprogramada',
            name='origen',
            field=models.CharField(choices=[('M4D', 'M4D'), ('M2D', 'M2D'), ('M6D', 'M6D'), ('AOD', 'AOD'), ('TLM', 'TLM'), ('FUD', 'FUD')], max_length=10),
        ),
    ]
