# Generated by Django 4.2.28 on 2026-02-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0005_alter_rutaprogramada_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaprogramada',
            name='lugar_vales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
