# Generated by Django 4.2.28 on 2026-02-18 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='consumo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='servicio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogos.servicio'),
            preserve_default=False,
        ),
    ]
